# ------------------------------------------------------------
# |                                                          |
# |      _  _______        __     __    _____   ____         |
# |     | ||___ ___|      |  \   /  |  / ____| |  _ \        |
# |     | |   | |   ___   | |\\ //| | | (___   | | \ \       |
# |     | |   | |  / _ \  | | \_/ | |  \___ \  | |  ) )      |
# |     | |   | | | (_) | | |     | |  ____) | | |_/ /       |
# |     |_|   |_|  \___/  |_|     |_| |_____/  |____/        |
# |                                                          |
# |                                                          |
# ------------------------------------------------------------
# |                 +==================+                     |
# |                 |   ServersSlots   |                     |
# |                 |------------------|                     |
# |                 |        1.0       |                     |
# |                 |------------------|                     |
# |                 |  PolsatGraniePL  |                     |
# |                 +==================+                     |
# ------------------------------------------------------------
#
# Hello, if you need help or have an idea that will improve our plugin,
#                   then be sure to contact us:
#
#  IToMSD Website: https://itomsd.com/
#  IToMSD Discord: https://dc.itomsd.com/
#  IToMSD SpigotMC: https://www.spigotmc.org/resources/authors/itomsd.1983449/




# max-players = Limit of players on the server

max-players: 20




# Messages

no_permission: '&cYou do not have permission to perform this command.'
full_server: '&cServer is full!'